name: Déployer CV sur Github Pages

on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Déployer le site web
        with:
          branch: main

